apiVersion: v1
kind: Template
metadata:
  name: jenkins-template
objects:
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: jenkins-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: jenkins
    spec:
      template:
        metadata:
          labels:
            app: jenkins
        spec:
          containers:
            - name: jenkins
              image: jenkins/jenkins
              ports:
                - containerPort: 8080
                  name: http
              volumeMounts:
                - mountPath: /var/jenkins_home
                  name: jenkins-pv
          volumes:
            - name: jenkins-pv
              persistentVolumeClaim:
                claimName: jenkins-pvc
  - kind: Service
    apiVersion: v1
    metadata:
      name: jenkins
    spec:
      ports:
        - name: http
          port: 8080
          targetPort: 8080
      selector:
        app: jenkins
