spec:
  template:
    spec:
      containers:
        - name: nginx-container
          image: my-nginx-app
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config
        - name: html-volume
          configMap:
            name: nginx-html
