apiVersion: v1
kind: Template
metadata:
  name: nginx-template
objects:
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: nginx-app
    spec:
      replicas: 1
      selector:
        app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
            - name: nginx-container
              image: your-nginx-image
              ports:
                - containerPort: 80
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/nginx/conf.d/
                - name: html-volume
                  mountPath: /usr/share/nginx/html
          volumes:
            - name: config-volume
              configMap:
                name: nginx-config
            - name: html-volume
              configMap:
                name: nginx-html
  - kind: Service
    apiVersion: v1
    metadata:
      name: nginx-service
    spec:
      selector:
        app: nginx
      ports:
        - protocol: TCP
          port: 80